Autogenerated Dockerfiles
Signed-off-by: Trong Nghia Nguyen <nghiant2710@gmail.com>

diff --git a/balena-base-images/aarch64/debian/jessie/build/Dockerfile b/balena-base-images/aarch64/debian/jessie/build/Dockerfile
--- a/balena-base-images/aarch64/debian/jessie/build/Dockerfile
+++ b/balena-base-images/aarch64/debian/jessie/build/Dockerfile
@@ -22,7 +22,32 @@ RUN sed -i '/debian-security/{s/^/#/}' /etc/apt/sources.list \
         echo 'iproute2'; \
       fi \
   ) \
-  && rm -rf /var/lib/apt/lists/*
+  && rm -rf /var/lib/apt/lists/* \
+  && echo '#!/bin/sh\n\
+set -e\n\
+set -u\n\
+export DEBIAN_FRONTEND=noninteractive\n\
+n=0\n\
+max=2\n\
+until [ $n -gt $max ]; do\n\
+  set +e\n\
+  (\n\
+    apt-get update -qq &&\n\
+    apt-get install -y --no-install-recommends "$@"\n\
+  )\n\
+  CODE=$?\n\
+  set -e\n\
+  if [ $CODE -eq 0 ]; then\n\
+    break\n\
+  fi\n\
+  if [ $n -eq $max ]; then\n\
+    exit $CODE\n\
+  fi\n\
+  echo "apt failed, retrying"\n\
+  n=$(($n + 1))\n\
+done\n\
+rm -r /var/lib/apt/lists/*' > /usr/sbin/install_packages \
+  && chmod 0755 "/usr/sbin/install_packages"
 
 # Install packages for build variant
 RUN apt-get update && apt-get install -y --no-install-recommends \
@@ -95,3 +120,6 @@ APT::Install-Suggests "0";\n\
 quiet "true";' > /etc/apt/apt.conf.d/01_buildconfig
 
 RUN mkdir -p /usr/share/man/man1
+
+COPY entry.sh /usr/bin/entry.sh
+ENTRYPOINT ["/usr/bin/entry.sh"]
